api_platform:
    enable_docs: true
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Dto', '%kernel.project_dir%/src/Resource' ]
    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    # Good defaults for REST APIs
    defaults:
#        uri_prefix: /api
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
